

import argparse
import glob
import os

import pandas as pd

STANDARD_SEEDS = [0, 42, 64, 7, 123]
SHIFT = {0: 1, 42: 43, 64: 65, 7: 8, 123: 124}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--logs_dir", default="./logs")
    ap.add_argument("--out", default="scripts/rerun_shifted_seeds.sh")
    args = ap.parse_args()

    csv_paths = glob.glob(os.path.join(args.logs_dir, "*experimental_logs.csv"))
    df = pd.concat([pd.read_csv(f) for f in csv_paths], ignore_index=True)
    df = df[df["info"].fillna("").str.contains("_final")].copy()
    df["seed"] = df["info"].str.extract(r"seed(\d+)").astype(int)
    df["source"] = df.train_dataset.str.split("_").str[0]
    df["target"] = df.train_dataset.str.split("_").str[1]

    have = df.groupby(["train_dataset", "model"])["seed"].apply(set)

    commands = []
    for (pair, model), seeds in have.items():
        src, tgt = pair.split("_")
        missing = [s for s in STANDARD_SEEDS if s not in seeds]
        for old_seed in missing:
            new_seed = SHIFT[old_seed]
            tag = f"final_s{new_seed}"
            commands.append(
                f'$PY CMAPSS_DA.py --model_name "{model}" --dataset_name CMAPSS '
                f'--Data_id_CMAPSS "{src}" --Data_id_CMAPSS_test "{tgt}" '
                f'--seed {new_seed} --save_path "{tag}" '
                f'--info "{model}_{src}_{tgt}_seed{new_seed}_final" '
                f'|| echo "FAIL {pair} {model} seed{new_seed}"'
            )

    header = f"""#!/usr/bin/env bash
# Auto-generated by scripts/gen_shifted_seed_reruns.py -- {len(commands)} reruns
# at shifted seed values (see SHIFT mapping in that script), replacing slots
# purged by scripts/purge_flagged_anomalies.py.
set -uo pipefail
cd "$(dirname "$0")/.."
export CUDA_VISIBLE_DEVICES="${{1:-0}}"
PY=$(command -v python3 || command -v python)
"""
    with open(args.out, "w") as f:
        f.write(header + "\n" + "\n".join(commands) + "\n")
    os.chmod(args.out, 0o755)
    print(f"wrote {len(commands)} rerun commands -> {args.out}")


if __name__ == "__main__":
    main()
